version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
  server:
    build:
      context: ./server
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 3001:3001
  db:
    ports:
      - 27017:27017
    restart: unless-stopped
    # logging:
    #   options:
    #     max-size: 1g
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=mongoadmin
    #   - MONGO_INITDB_ROOT_PASSWORD=bdung
    image: mongo
  db-admin:
    ports:
      - 3002:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    restart: unless-stopped
    depends_on:
      - db
    image: mongo-express